// Generated by CoffeeScript 1.10.0
(function() {
  var HelloView,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  HelloView = (function(superClass) {
    extend(HelloView, superClass);

    function HelloView() {
      return HelloView.__super__.constructor.apply(this, arguments);
    }

    HelloView.content = function(params) {
      return this.div( (function(_this) {
        
        return function() {
          _this.div (params.greeting);
          _this.label ( {"for": 'name'}, "What is your name? ");
          
          _this.div (function() {
            _this.input({ name: 'name', outlet: 'name'});
            return _this.button({ click: 'sayHello'}, "That's My Name");
          });
          
          return _this.div({ outlet: "personalGreeting"});
        };
        
      })(this));
      
    };

    HelloView.prototype.initialize = function(params) {
      return this.greeting = params.greeting;
    };

    HelloView.prototype.sayHello = function() {
      return this.personalGreeting.html(this.greeting + ", " + (this.name.val()));
    };

    return HelloView;

  })(View);

  $('body').append(new HelloView({
    greeting: "Hi there"
  }));

}).call(this);
