// Generated by CoffeeScript 1.10.0
(function() {
  var ClientMain, EventEmitter, fork, path;

  EventEmitter = require('events').EventEmitter;

  fork = require('child_process').fork;

  path = require('path');

  console.log('client-main.coffee!');

  ClientMain = function() {
    return {
      init: function() {
        var childFilePath;
        this.emitter = new EventEmitter;
        childFilePath = path.join(__dirname, 'client-child-simple.js');
        console.log("childFilePath: " + childFilePath);
        this.childProcess = fork(childFilePath);
        return this.childProcess.on('message', function(data) {
          console.log('client-view: from client-child');
          return console.log(data);
        });
      }
    };
  };

  module.exports = new ClientMain;

}).call(this);
