// Generated by CoffeeScript 1.10.0
(function() {
  var ClientMain, EventEmitter, fork, path,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  EventEmitter = require('events').EventEmitter;

  fork = require('child_process').fork;

  path = require('path');

  console.log('client-main.coffee!');

  ClientMain = (function() {
    function ClientMain() {
      this.init = bind(this.init, this);
    }

    ClientMain.life = 'hard';

    ClientMain.prototype.init = function() {
      var childFilePath;
      this.emitter = new EventEmitter;
      childFilePath = path.join(__dirname, 'client-child-complete-b.js');
      console.log("childFilePath: " + childFilePath);
      this.childProcess = fork(childFilePath);
      this.childProcess.on('message', (function(_this) {
        return function(data) {
          console.log('client-view: from client-child');
          return console.log(data);
        };
      })(this));
      return console.log(ClientMain);
    };

    return ClientMain;

  })();

  module.exports = new ClientMain;

}).call(this);
